nucleos_dompdf:
    defaults:
<<<<<<< ours
        chroot: '%kernel.project_dir%/public/assets' # See https://github.com/dompdf/dompdf/wiki/Usage#security-restrictions-for-local-files
        isRemoteEnabled: true
=======
        chroot: '%kernel.project_dir%/public/assets' # See https://github.com/dompdf/dompdf/wiki/Usage#options
>>>>>>> theirs
        logOutputFile: '' # Prevent creating `/tmp/log.htm` which causes problems in some server configurations
