vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       programs_images:
           uri_prefix: /images/programs
           upload_destination: '%kernel.project_dir%/public/images/programs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       about_images:
           uri_prefix: /images/about
           upload_destination: '%kernel.project_dir%/public/images/about'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       links_svg:
           uri_prefix: /images/links
           upload_destination: '%kernel.project_dir%/public/images/links'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       categories_svg:
           uri_prefix: /images/categories
           upload_destination: '%kernel.project_dir%/public/images/categories'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       courses_videos:
           uri_prefix: /videos/courses
           upload_destination: '%kernel.project_dir%/public/videos/courses'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       courses_files:
           uri_prefix: /uploads/courses
           upload_destination: '%kernel.project_dir%/public/uploads/courses'
           namer: App\Service\TwigFileNamer
           delete_on_update: true
           delete_on_remove: true
       avatars_images:
           uri_prefix: /images/avatars
           upload_destination: '%kernel.project_dir%/public/images/avatars'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       appointments_images:
           uri_prefix: /images/appointments
           upload_destination: '%kernel.project_dir%/public/images/appointments'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true